// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: videoService.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	FindVideosByTime(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoDetailResponse, error)
	FindVideosByUser(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoDetailResponse, error)
	FindVideosByIds(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoDetailResponse, error)
	CreateVideo(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) FindVideosByTime(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoDetailResponse, error) {
	out := new(VideoDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.VideoService/FindVideosByTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) FindVideosByUser(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoDetailResponse, error) {
	out := new(VideoDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.VideoService/FindVideosByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) FindVideosByIds(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoDetailResponse, error) {
	out := new(VideoDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.VideoService/FindVideosByIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) CreateVideo(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.VideoService/CreateVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility
type VideoServiceServer interface {
	FindVideosByTime(context.Context, *VideoRequest) (*VideoDetailResponse, error)
	FindVideosByUser(context.Context, *VideoRequest) (*VideoDetailResponse, error)
	FindVideosByIds(context.Context, *VideoRequest) (*VideoDetailResponse, error)
	CreateVideo(context.Context, *VideoRequest) (*CommonResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (UnimplementedVideoServiceServer) FindVideosByTime(context.Context, *VideoRequest) (*VideoDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindVideosByTime not implemented")
}
func (UnimplementedVideoServiceServer) FindVideosByUser(context.Context, *VideoRequest) (*VideoDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindVideosByUser not implemented")
}
func (UnimplementedVideoServiceServer) FindVideosByIds(context.Context, *VideoRequest) (*VideoDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindVideosByIds not implemented")
}
func (UnimplementedVideoServiceServer) CreateVideo(context.Context, *VideoRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVideo not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_FindVideosByTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FindVideosByTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VideoService/FindVideosByTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FindVideosByTime(ctx, req.(*VideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_FindVideosByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FindVideosByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VideoService/FindVideosByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FindVideosByUser(ctx, req.(*VideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_FindVideosByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FindVideosByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VideoService/FindVideosByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FindVideosByIds(ctx, req.(*VideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_CreateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).CreateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VideoService/CreateVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).CreateVideo(ctx, req.(*VideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindVideosByTime",
			Handler:    _VideoService_FindVideosByTime_Handler,
		},
		{
			MethodName: "FindVideosByUser",
			Handler:    _VideoService_FindVideosByUser_Handler,
		},
		{
			MethodName: "FindVideosByIds",
			Handler:    _VideoService_FindVideosByIds_Handler,
		},
		{
			MethodName: "CreateVideo",
			Handler:    _VideoService_CreateVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "videoService.proto",
}
